[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
uniffi = { version = "0.31", features = ["cli"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"
