[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", branch = "main", features = ["cli"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"
